### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'string'

### ISSUE THREAD

**Issue by Tas-sos** [mdonnalley/pyGoogleSearch#4]
I have a **Ubuntu GNU/Linux server 14.04.5 LTS**, with **Python 3.4.3** and installed your package in [virtual environment](https://docs.python.org/3/tutorial/venv.html), by typing : `pip install pyGoogleSearch==2.5`

I use your package in a django app, and unfortunately I got the following error message :

```
Traceback (most recent call last):
  File "/home/user/djangoApps/testApp/.venv/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
    
  File "/home/user/djangoApps/testApp/.venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
    
  File "/home/user/djangoApps/testApp/.venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
    
  File "/home/user/djangoApps/testApp/myapp/views.py", line 125, in create_pdf
    related_articles = search("ok")
    
  File "/home/user/djangoApps/testApp/myapp/google/search.py", line 54, in search
    raw_web_data = Google(a_question).search()
    
  File "/home/user/djangoApps/testApp/.venv/lib/python3.4/site-packages/pyGoogleSearch/Google.py", line 40, in search
    raw_total_results = self.big_soup.find('div', attrs={'class': 'sd'}).string
    
AttributeError: 'NoneType' object has no attribute 'string'
```

On Debian 9 ( _with Python 3.**5**.2_ ) or Ubuntu 16.04 LTS ( _with Python 3.**5**.3_ ) i never had problems!

**Comment by Tas-sos** [comment]
Now I have exactly the same problem in another VM on **Ubuntu _Server_ 16.04.3 LTS** with **Python 3.5.2**.
```
Traceback (most recent call last):
  File "/home/user/djangoApps/testApp/.venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)


  File "/home/user/djangoApps/testApp/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)


  File "/home/user/djangoApps/testApp/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)


  File "/home/user/djangoApps/testApp/myapp/views.py", line 131, in create_pdf
    related_articles = search(project_data['title'])


  File "/home/user/djangoApps/testApp/myapp/google/search.py", line 54, in search
    raw_web_data = Google(a_question).search()

  File "/home/user/djangoApps/testApp/.venv/lib/python3.5/site-packages/pyGoogleSearch/Google.py", line 40, in search
    raw_total_results = self.big_soup.find('div', attrs={'class': 'sd'}).string

AttributeError: 'NoneType' object has no attribute 'string'
```

**pip list:**
<details>
<summary>pip list</summary>

```
beautifulsoup4 (4.6.0)
certifi (2018.1.18)
chardet (3.0.4)
Django (2.0)
idna (2.6)
pip (8.1.1)
pkg-resources (0.0.0)
pyGoogleSearch (2.5)
pytz (2018.3)
requests (2.18.4)
setuptools (20.7.0)
urllib3 (1.22)
```
</details>
<br>

It's' unbelievable, what happening ?

**Comment by Tas-sos** [comment]
I found out that I received this message because, Google wonders if I'm a bot and so it puts me to solve the **CAPTCHA**. 
What can i do to bypass this problem ?

P.S. : **This only happens when I run the application through a web server!**

Thank you!
